[package]
name = "fsb-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["hsgamer"]
license = "MIT"
description = "A thesis template for FSB (FPT School of Business and Technology) students."
repository = "https://github.com/hsgamer/fsb-thesis-template"
categories = ["thesis", "report"]
disciplines = ["computer-science", "engineering"]

[template]
path = "template"
entrypoint = "main.typ"
